### ISSUE TITLE
Consistency in user treatment

### ISSUE THREAD

**Issue by nudzg** [BlackBoxVision/ra-language-spanish#10]
Hello,

Some strings treat the user with formal style (as in "_usted_"), others informal ("_tú_"). I think translation strings should be consistent, all formal, all informal, but not mixed.

Tried to fix it here:

https://github.com/nudzg/ra-language-spanish/commit/740aa0c47381427873f6208d2087cb2918b484c3

Thank you!

**Comment by JonatanSalas** [comment]
Would you mind making a PR?
