### ISSUE TITLE
Replace auth.sign_in with 'Acceder'?

### ISSUE THREAD

**Issue by kfern** [BlackBoxVision/ra-language-spanish#4]
IMHO 'Acceder' is better than 'Ingresar' in auth.sign_in

**Comment by JonatanSalas** [comment]
Okay, I will change it today!

**Comment by JonatanSalas** [comment]
v1.0.3 has 'Acceder' as value in **sign_in** key, so please update!

**Comment by kfern** [comment]
Thanks
