### ISSUE TITLE
react-admin v2

### ISSUE THREAD

**Issue by kfern** [BlackBoxVision/ra-language-spanish#6]
Hi!

Do you have a date scheduled to update the translation to version 2?

**Comment by JonatanSalas** [comment]
Not yet, but, if you want to contribute, PRs are really welcome!

**Comment by JonatanSalas** [comment]
@kfern I'm working on it!

**Comment by JonatanSalas** [comment]
@kfern I have added support for react-admin! 

```npm i aor-language-spanish@2.0.0```
